- httpstan/stan.pyx
- httpstan/utils.py
- tests/test_linear_regression.py
The helper function which converts multi-dimensional data into the
flattened data (column-major) required by Stan is
``httpstan.utils._split_data``.
Closes #1
> Add support multi-dimensional data.

- .travis.yml
- httpstan/compile.pyx
- httpstan/libcpp.pxd
> Compatibility fixes for GCC 4.8.2

- httpstan/anonymous_stan_model_services.pyx.template
- httpstan/views.py
- tests/test_eight_schools.py
Endpoint which returns param names and dims will also return
constrained param names.
> Include constrained param names in param details

- httpstan/cache.py
- httpstan/main.py
- httpstan/models.py
- httpstan/views.py
- tests/test_bernoulli.py
Relatively minor change. Sets STAN_THREADS macro and removes lock.
> Draw samples in parallel using system threads.

- httpstan/routes.py
- httpstan/views.py
- tests/test_health_check.py
Allows clients to check if server is up.
> Add simple `health` endpoint

- httpstan/services_stub.py
- tests/test_bernoulli.py
Add test making sure that parallel sampling works as intended.  Remove a
call to `ensure_future` which doesn't do anything useful and might
create complications.
> Add parallelism test, remove useless `ensure_future`.

- httpstan/__main__.py
- httpstan/main.py
- tests/conftest.py
- tests/test_arguments.py
- tests/test_bernoulli.py
- tests/test_eight_schools.py
- tests/test_health_check.py
- tests/test_linear_regression.py
- tests/test_programs.py
- tests/test_programs_actions.py
- tests/test_server.py
If someone is using port 8080, for example, httpstan will try 8081.
Searches all ports from 8080 to 9000.  This behavior should be familiar
from Jupyter notebook.
> HTTP server picks an available port to listen on.

- httpstan/routes.py
- httpstan/views.py
- tests/test_compile.py
> Return compile errors to client

- httpstan/anonymous_stan_model_services.pyx.template
- httpstan/services/arguments.py
- httpstan/services_stub.py
- tests/helpers.py
- tests/test_transformed_data_rng.py
Random number generation in the transformed data block uses the random
seed which is used by the sampling algorithms. This is essential for
reproducibility.
> Consistent random number generation in transformed data

- httpstan/main.py
- requirements.txt
> use uvloop instead of cpython event loop

- httpstan/models.py
- tests/test_programs.py
> shorten model ids, include httpstan version

- httpstan/cache.py
> cache: use version-specific cache

- httpstan/services_stub.py
- httpstan/views.py
This simplifies the code and will likely speed things up by eliminating
an `async for` loop and async overhead.
> Eliminate async for loop, write directly to file

- httpstan/services_stub.py
- httpstan/views.py
Add Stan C++ progress updates, as they arrive, to Operation `metadata`.
> Periodically update Operation with sampling progress

- .travis.yml
- test-requirements.txt
- tox.ini
> CI: add test coverage report

- httpstan/main.py
- requirements.txt
uvloop does not work on Windows.
Closes #141
> fix: disable uvloop on windows and PyPy

- httpstan/models.py
Cosmetic. Makes subsequent changes easier to understand.
> refactor: move utility functions outside context manager

- httpstan/models.py
Moves closer to supporting Windows.
> fix: Windows-compat temporary directory creation

- CONTRIBUTING.rst
- doc/source/code-of-conduct.rst
> Add code of conduct

- doc/source/code-of-conduct.rst
Corrects previous commit which was added by mistake.
Closes #50
> fix: add Code of Conduct

- httpstan/services/cmdstan-help-all.json
> fix: Update cmdstan-help-all.json for CmdStan v2.20.0

- requirements.txt
> fix: Use pbr 5.x, matches pystan

- test-requirements.txt
- tox.ini
This will not hurt and may help current continuous integration problems.
> fix: Update tox version

- httpstan/models.py
Makes it easier to inspect tempfiles and also remove the old ones (Windows problem).
> prefix to 'httpstan_' for tempfiles

- .appveyor.yml
- tests/test_callbacks_writer_parser.py
- tests/test_programs.py
> Enable Windows tests

- httpstan/__main__.py
- httpstan/cache.py
- httpstan/callbacks_writer_parser.py
- httpstan/main.py
- httpstan/models.py
- httpstan/routes.py
- httpstan/schemas.py
- httpstan/services/arguments.py
- httpstan/services_stub.py
- httpstan/views.py
- scripts/parse_cmdstan_help.py
- tests/conftest.py
- tests/helpers.py
- tests/test_arguments.py
- tests/test_bernoulli.py
- tests/test_callbacks_writer_parser.py
- tests/test_compile.py
- tests/test_eight_schools.py
- tests/test_fits.py
- tests/test_generated_quantities.py
- tests/test_generated_quantities_rng.py
- tests/test_health_check.py
- tests/test_linear_regression.py
- tests/test_openapi_spec.py
- tests/test_programs.py
- tests/test_transformed_data_rng.py
- tox.ini
> fix: Add typing information for httpstan

- .gitignore
- .travis.yml
- Makefile
- httpstan/cache.py
- httpstan/callbacks_writer_parser.py
- httpstan/models.py
- httpstan/services/arguments.py
- httpstan/services_stub.py
- httpstan/views.py
- mypy.ini
- test-requirements.txt
- tests/helpers.py
- tests/test_callbacks_writer_parser.py
- tox.ini
Uses `mypy-protobuf` to generate stub files for the generated protobuf
module.
> tests: Type check everything using mypy

- .gitignore
- Makefile
- doc/source/index.rst
- scripts/build_docs.sh
- tox.ini
This may need some additional adjustment to work with readthedocs. Let's hope not.
> ci: Simplify docs building, fix sphinx errors

- .gitignore
- doc/source/conf.py
- doc/source/http_rest_api.rst
- doc/source/index.rst
- doc/source/openapi.rst
- httpstan/routes.py
- httpstan/schemas.py
- httpstan/stan.pxd
- httpstan/views.py
- requirements.txt
- scripts/build_docs.sh
- test-requirements.txt
- tests/test_bernoulli.py
- tests/test_compile.py
- tests/test_openapi_spec.py
- tests/test_schemas.py
Three related packages updated:
- marshmallow
- webargs
- apispec
> fix: Use Marshmallow 3.x for request validation

- .travis.yml
- tox.ini
Avoids running all tests twice.
> ci: Remove separate `coverage` test

- .readthedocs.yml
- doc/source/conf.py
- httpstan/__init__.py
- tox.ini
This speeds up testing and will allow us to use readthedocs.
> docs: Allow docs generation without package installed

- docs-requirements.txt
A variety of unnecessary packages were being installed.
> docs: Trim required packages for docs building

- Makefile
- httpstan/models.py
> fix: Adjust gcc ABI compatibility settings

- .travis.yml
- codecov.yml
> ci: enable codecov

- doc/developers.rst
- httpstan/__init__.py
- pyproject.toml
- tests/test_httpstan.py
I neglected to update the version numbers.
Good news is that the ABI fix seems to work.
> fix: Update version numbers

- .travis.yml
Thanks to @ahartikainen for the macOS specific fix.
> ci: Test on macOS

- CONTRIBUTING.rst
- README.rst
- doc/development_setup.rst
- doc/installation.rst
Contains other minor documentation improvements as well.
Closes #247
Closes #284
> docs: Update development instructions

- doc/developers.rst
> docs: Check that new release does not break pystan

- tests/test_logger_callback.py
> test: Check that progress logger callback is being called

- .gitignore
- tests/test_arguments.py
- tests/test_bernoulli.py
- tests/test_cache.py
- tests/test_eight_schools.py
- tests/test_generated_quantities_rng.py
- tests/test_utils.py
Implements new tests for failures.
> test: increase testing cases

- .travis.yml
- Makefile
- httpstan/models.py
- pyproject.toml
- tests/test_cvodes.py
> feat: Add support for CVODES-requiring Stan models

- Makefile
Previous Makefile rules had flaws that led to targets being rebuilt
unnecessarily.
> fix: Improve Makefile rules

- httpstan/services_stub.py
Stan C++ sends us data via the Unix domain socket. We do not need to use
select to wait until there is data to receive.
This version is simpler. It also strongly resembles the code used
when we waited on a thread-safe boost queue.
> fix: Simplify socket code, select module not needed

- .travis.yml
Use the new version that travis-ci.com asks for.
> ci: Update travis config

- Makefile
Using directories as targets in a Makefile creates problems.
We use order-only prerequisites to solve this problem.
The problem and the solution are discussed here:
https://stackoverflow.com/a/13418059
Closes #343
> fix: Use order-only prerequisites for dirs in Makefile

- httpstan/__init__.py
- pyproject.toml
Includes fix to include shared libraries in the wheel.
> chore: Update version

- .travis.yml
- Makefile
- build.py
- httpstan/models.py
- pyproject.toml
Update the Stan and Math code (and associated libraries).
> feat: Update Stan to 2.23.0 and Stan Math to 3.2.0

- doc/conf.py
- docs-requirements.txt
- tox.ini
No problems expected here.
Closes #391
> chore: Update sphinx version

- httpstan/__init__.py
- pyproject.toml
Update version to 2.0.3. macOS wheels should be fixed.
> chore: Update version to 2.0.3

- httpstan/services_stub.py
- httpstan/views.py
The services_stub.call function takes responsibility for
writing the messages it gets from Stan to disk. Previously
the `call` function did some writing but closing the buffer
was handled elsewhere.
Closes #352
Assumes #410 is merged.
> refactor: Write fit messages in single place

- httpstan/compile.py
- httpstan/compile.pyi
Remove old Cython code which is no longer used.
> fix: Remove unused code

- httpstan/cache.py
Use `gzip` to compress and decompress cache with the default settings.
> feat: compress/decompress cache with gzip

- tests/test_linear_regression.py
Add seed for linear regression test.
> test: add seed

- README.rst
Updates required Python version. Representation
of model information also updated.
Closes #456
> docs: Update README to reflect current version

- httpstan/openapi.py
- httpstan/routes.py
- httpstan/views.py
- tests/test_delete_model.py
Allow users to delete a model. Deleting a model
also removes all associated fits.
> feat: Allow users to delete a model

- httpstan/cache.py
- httpstan/openapi.py
- httpstan/routes.py
- httpstan/views.py
- tests/test_delete_fit.py
Allow users to delete fits saved in cache.
Closes #435
> feat: Allow users to delete fits

- httpstan/__init__.py
- pyproject.toml
> chore: Bump version

- .github/stale.yml
Stale bot does not seem to be working. Use a standard config. Perhaps it
will fix the problem.
> ci: Update stale bot config

- Makefile
> feat: Update Stan to 2.25.0

- tests/test_nan_inf.py
Verify that nan, inf, and -inf values are correctly
serialized.
> test: Verify (de)serialization of nan, inf, -inf

- tests/test_large_model.py
Check that a model with many parameters (160) works.
Prompted by a unusual bug in late 2020.
> test: Verify a model with many parameters works

- .github/workflows/main.yml
Run tests in GitHub Actions, testing against Linux (Ubuntu 20.04) and macOS (10.15 and 11.0).
> ci: github actions

- httpstan/views.py
Describe `Operation` in greater detail. Indicate
that users should learn about whether not a sampling run
has finished by checking the relevant operation.
Closes #413
> docs: Describe Operation in greater detail.

- httpstan/build_ext.py
- httpstan/services_stub.py
- httpstan/views.py
Exclude several sections of code from coverage calculation.  These
sections contain code that is repetitive or which is related to
debugging.
> test: Exclude parts of code from coverage calculation

- .coveragerc
- .github/workflows/main.yml
- httpstan/models.py
- httpstan/schemas.py
- httpstan/views.py
- pyproject.toml
Adjust ignored code for coverage calculation. Completes
work started in commit 5417907.
Closes #442
> Final adjustment of code which is ignored during coverage calculation

- httpstan/stan_services.cpp
Removes unncessary calls to the memcpy (we already copied from a vector of
doubles to a vector of stan::math::var). Slight reordering to return the
log probability after deleting model and var_context variables.
> fix: Remove unnecessary memcpy and reorder logprob

- httpstan/views.py
Minor changes to the docstrings of log_prob and log_prob_grad.
> docs: Correct log_prob and log_prob_grad docstring

- doc/contributing.rst
Make httpstan's goals and non-goals clearer.
> docs: Make goals and non-goals clearer

- .github/workflows/main.yml
- doc/installation.rst
I believe poetry has solved the problem which #466 addressed.
> Update poetry and associated docs

- README.rst
- doc/index.rst
Update Zenodo citation. Add BibTeX citation.
> docs: Update Zenodo citation

- httpstan/views.py
- pyproject.toml
Update httpstan's dependencies.
> chore: Update dependencies

- httpstan/cache.py
- httpstan/compile.py
- httpstan/models.py
- tests/test_cache.py
Switch to use pathlib.Path as the main way to handle path information.
> Increase pathlib.Path use

- .github/workflows/main.yml
> ci: Test under Python 3.9

- README.rst
- doc/index.rst
> docs: Fix typo in README

- httpstan/views.py
- tests/test_fits.py
Fix assertation for 0-dimensional arrays.
Fixes #546
> fix: Correct handling for 0-dim arrays.

- .github/workflows/main.yml
- Makefile
Fix parallel execution with make. One rule needed to be updated.
Adjust CI script to use parallel execution so we know the problem
is solved.
> fix: Fix make parallel execution

- pyproject.toml
Add mjcarter to authors in pyproject.toml
> docs: Add mjcarter to authors

- README.rst
- doc/installation.rst
Indicate which C++ compilers we know work.
Closes #501
> docs: Add C++ compiler version requirement

- Makefile
- pyproject.toml
- tests/test_compile.py
Title says it all.
Do not merge until final 2.28 release.
> Update Stan to 2.28, bump version

- .github/workflows/main.yml
- Makefile
- httpstan/models.py
- pyproject.toml
Add Python 3.10 to the testing matrix.
> ci: Test Python 3.10

- Makefile
- doc/conf.py
- docs-requirements.txt
- httpstan/__init__.py
- httpstan/app.py
- httpstan/views.py
- pyproject.toml
- tests/test_compile.py
- tests/test_log_prob_grad.py
- tests/test_user_inits.py
> feat: Update Stan to 2.29.0, bump version

- Makefile
- pyproject.toml
> fix: Update Stan to 2.29.2, bump version

- httpstan/services_stub.py
A recent commit, `feat: Add context to initialization failed error`
included code that was not as clear as it could have been. This
commit improves code legibility.
> refactor: Improve code readability, init failed fix

- doc/developer_resources.rst
Making a release is simple. This commit documents the steps currently
involved.
> docs: Add a bit of information about release steps.

- Makefile
- pyproject.toml
> fix: Bugfix release of stanc3

- pyproject.toml
Use proper TOML. Validation changed in recent version of poetry.
> fix: Use valid TOML in pyproject.toml

- httpstan/services_stub.py
> Fix file descriptor leak

- doc/developer_resources.rst
Must update version in pyproject.toml.
> docs: Add missing step to release instructions

- pyproject.toml
Update mypy to address Python 3.10.7 issue.
> test: Update mypy

- .github/workflows/main.yml
Poetry 1.2 appeared not too long ago. Use it.
~This needs to be rebased before merging.~
> ci: Use newer poetry in CI

- doc/installation.rst
Fix syntax error in restructuredtext link.
> docs: Fix restructuredtext link

- Makefile
- pyproject.toml
Update Stan to 2.32.2, bump httpstan version.
> feat: Update Stan to 2.32.2, bump version

- .github/workflows/main.yml
- Makefile
- docs-requirements.txt
- httpstan/services_stub.py
- pyproject.toml
- tests/test_bernoulli.py
- tests/test_compile.py
- tests/test_cvodes.py
- tests/test_eight_schools.py
- tests/test_fixed_param.py
- tests/test_large_model.py
Update Stan to 2.33.0, bump httpstan version.
> feat: Update Stan to 2.33.0, bump version

- README.rst
Note build requirement for poetry<2
> docs: Note build requirement for poetry<2
