stan-dev/httpstan

httpstan/cache.py

By default sqlite3 optimizes for compatibility. We can assume that a
user with Python 3.6 available has a non-ancient version of sqlite3.

sqlite3 fixes: turn on write-ahead-log

---

httpstan/anonymous_stan_program_services.pyx.template
httpstan/routes.py
httpstan/views.py
tests/test_bernoulli.py

Adds endpoint ``/v1/programs/{programs_id}/params`` (soon to be renamed
to ``/v1/models/{model_id}/params``). OpenAPI documentation added.
Closes #28.

Adds endpoint for getting param names and dims

---

httpstan/models.py

mypy currently has some difficulties inferring types with ``open``.

typing: short-term mypy fix for `open`

---

README.rst

Add note to README about how ``protoc`` is required when installing from
source. Strictly speaking this is a build requirement.
Closes #17

DOC: how to install `protoc` when building

---

httpstan/services_stub.py
tests/test_programs_actions.py

Stan C++ passes data to httpstan via a boost spsc_queue. Stan sends a
lot of messages so the previous capacity of 10,000 was far too small.
New capacity is 10,000,000.

Increase spsc queue capacity

---

tests/test_bernoulli.py

Travis-ci workers report having more than one core available but
sampling is about as slow as if there were only one core. The speed test
now only requires that two chains take less time than sampling two
chains serially.

TST: relax parallelism speed test

---

httpstan/callbacks_writer_parser.py
protos/callbacks_writer.proto
tests/helpers.py
tests/test_callbacks_writer_parser.py
tests/test_programs_actions.py

Previously a `map` was used which did not guarantee order. We need
to keep information about the order of parameters coming from Stan
because matrix and array parameters are stored flat in column-major
order.

Protobuf uses ordered representation of draws

---

tests/test_bernoulli.py

Travis CI's CPUs do not appear to be very powerful. Increasing
the number of warmup draws should avoid the error that occurs
when two (low-power) cpus sampling in parallel take (slightly) more than twice as
long as a single CPU sampling serially.

TST: avoid travis errors due to underpowered cpus

---

requirements.txt
test-requirements.txt

Updates `requirements.txt` and `test-requirements.txt`. Should help
avoid surprises when a version of a package is released with breaking
changes.

Limit versions of packages used

---

CHANGES.rst
README.rst
doc/source/changelog.rst
doc/source/index.rst
doc/source/release-howto.rst
doc/source/updating-stan-source.rst
scripts/download_wheels.sh

- release HOWTO updates, including a script to help download wheels.
- fixed update stan source update instructions
- minor README update, note Windows currently unsupported
- remove changelog for the moment (no public releases yet)

doc: documentation updates

---

httpstan/models.py
httpstan/views.py
tests/test_arguments.py

Two radically different functions shared the same name
(`load_model_extension_module`). Renames one of them.

rename module import function to avoid confusion

---

README.rst
httpstan/cache.py
httpstan/compile.pyx
httpstan/fits.py
httpstan/models.py
httpstan/routes.py
httpstan/schemas.py
httpstan/views.py
tests/helpers.py
tests/test_arguments.py
tests/test_bernoulli.py
tests/test_compile.py
tests/test_eight_schools.py
tests/test_fits.py
tests/test_health_check.py
tests/test_linear_regression.py
tests/test_programs.py
tests/test_transformed_data_rng.py
tox.ini

Minor changes superficially. Big changes include:
- Fits are no longer streamed to the client. The client retrieves the full output of Stan (length-prefixed Protocol Buffer messages) in a separate step.
- Fits are cached.
- Google's sensible [API Design Guide](https://cloud.google.com/apis/design/) is followed.
Closes #84 #83

Refactor API

---

httpstan/cache.py
httpstan/views.py

Sqlite3 has a maximum row size which prevents storing (very) large fits
in the sqlite3 database. Use the filesystem instead. Models are still
stored in sqlite3.

Cache fits in filesystem, not sqlite3

---

README.rst
httpstan/cache.py
httpstan/main.py
httpstan/routes.py
httpstan/schemas.py
httpstan/services_stub.py
httpstan/views.py
tests/helpers.py
tests/test_bernoulli.py
tests/test_compile.py
tests/test_eight_schools.py
tests/test_fits.py
tests/test_linear_regression.py

POST requests to the Fit endpoint return an Operation. This is
appropriate because (non-cached) Fits will be long-running. Client can
make requests to check on the status of an Operation. When the operation
is done, the client knows that it's safe to retrieve the
This commit also removes unneeded `Error` schema.
Better conforms to Google API Design Guide. The `Error` schema was
incorrectly adopted. It's part of a Google-specific
backward-compatibility scheme. We do not need backward-compatibility.
See https://cloud.google.com/apis/design/errors for details about the
schemas.
Closes #100

Fit endpoint returns long-running Operation

---

httpstan/anonymous_stan_model_services.pyx.template
requirements.txt
tests/test_fits.py
tests/test_generated_quantities.py
tests/test_generated_quantities_rng.py
tests/test_transformed_data_rng.py

Copy-and-paste humor error. Consider code generation for
most if not all of `anonymous_stan_model_services.pyx.template`.
Also ports several PyStan 2 tests.

fix: pass random seed to C++ model constructor

---

MANIFEST.in
scripts/update_stan_source.sh

Now removes `doc` directories within httpstan/lib. This is now required
because otherwise building a wheel on Windows will fail with an error
message about filenames which exceed some limit.

fix: update update Stan script

---

httpstan/anonymous_stan_model_services.pyx.template
tests/test_arguments.py

Only the default sampling algorithm, `hmc_nuts_diag_e_adapt` is
supported.
Also update a test to remove a reference to the unsupported algorithm.
Closes #180.

fix: Remove (currently) unsupported sampling algo

---

pyproject.toml

Fixes https://github.com/stan-dev/httpstan/issues/187
This PR adds `pyproject.toml` configure file for `black`. This enables the developer to call black <dir> and the correct configure is read from the `.toml` file. This also excludes stan folder, which speeds up black.
black httpstan

add pyproject.toml file

---

httpstan/models.py
tests/test_programs.py

Fixes https://github.com/stan-dev/pystan-next/issues/81
This PR will use the correct `.pyd` extension for compiled modules on Windows. After this change, model loading from cache works on Windows.

Use .pyd for Windows modules

---

httpstan/stan.pxd

This code should have been removed in commit 4925f8bf1a8c9e157bd3b6c52bf627b9d8270f1e.

fix: Remove unused code related to unused sampling algo

---

.travis.yml
httpstan/anonymous_stan_model_services.pyx.template
httpstan/models.py
httpstan/stan.pxd

Restore use of STAN_THREADS which was removed to address a compatibility
issue.
This code is not expected to work using certain versions of gcc.
Closes #191

fix: Restore STAN_THREADS

---

.travis.yml

Do not merge yet.
Also, needs to be rebased on master once #195 is merged.
Either travis does not actually export CXX or there is some `libstdc++` issue.

fix(ci): Test using clang on travis

---

tox.ini

We do not need to install httpstan in order to run `black`, `flake8`,
etc.
Closes #205

style: Make tox style checks faster

---

httpstan/models.py
setup.cfg

Two compiler defines are no longer needed with C++11.
Closes #188

fix: Remove unneeded compiler defines

---

requirements.txt

Do not install uvloop by default. Continue to use it if available.
Building uvloop sometimes fails on Linux. If Linux wheels for uvloop
become available, we might reconsider requiring it.

fix: Remove dependency on uvloop

---

.travis.yml

This will likely fail (on gcc tests). This is a good thing. `master` is in a failing state right now until the STAN_THREADS issue is resolved in detail.

test: Drop Python 3.6 tests, add 3.7 gcc test

---

httpstan/fits.py
httpstan/services/arguments.py
httpstan/services_stub.py
httpstan/views.py
tests/test_arguments.py

In the call to a sample function in stan services, `data` is no
different than `init` or `num_samples`. Previously, it was treated as
different from other arguments. This commit corrects this.
Closes #230

refactor: Treat `data` the same as other args in services call

---

httpstan/models.py
httpstan/views.py
tests/test_arguments.py

Previously a function existed which would load arbitrary bytes as an
extension module. This was really dangerous. The current code removes
this function without the loss of any functionality.
Closes #4

fix: Remove a dangerous function

---

.gitignore
CONTRIBUTING.rst
README.rst
build-requirements.txt
doc/conf.py
doc/index.rst
doc/installation.rst
doc/rest_api.rst
httpstan/models.py

Sphinx's autodoc really assumes you have installed the package. We cannot build the package on readthedocs because their workers do not have much memory. Use autoapi instead. It parses the docstrings without needing to build the package.
`autoapi`'s documentation is not particularly good or current.

docs: Fix typos and switch to autoapi

---

httpstan/stan.pxd
httpstan/views.py
tests/helpers.py
tests/test_sampling_initialization_failed.py

Previously (valuable) error messages were discarded when sampling
failed. This commit makes sure that the messages are saved.
Closes #272

fix: Save error messages when initialization fails

---

.travis.yml
tox.ini

We no longer use tox to create a virtualenv for each version of Python. This commit
removes unused parts of tox.ini.
Adds testing of Python 3.8 on travis.
Closes #283

ci: Remove unused tox tasks, update CI config

---

README.rst
httpstan/fits.py
httpstan/models.py

Previously, a model built under Python 3.8 would receive
the same id as a model built under Python 3.7.
Closes #288

fix: Give models from different `python`s distinct ids

---

doc/developers.rst
tests/test_httpstan.py

The original test wasn't a terribly useful check.
A more automated way of updating the version would be welcome.

fix: Drop test checking version number

---

.travis.yml

Downloading protobuf and Stan seem to cause build failures periodically.
These downloads can be cached.

ci: Use cache to avoid downloading tarballs

---

.travis.yml

The exit status of an if statement is the last command executed inside the if statement. This is why the previous version's test failures was not being picked up by travis.
Closes #321

ci: Properly record test exit codes

---

.travis.yml

This should make it harder to accidentally introduce a configuration
which allows test failures to go unnoticed.

ci: Make travis-ci config more robust

---

build.py
doc/conf.py
httpstan/fits.py
httpstan/models.py
httpstan/stan.pxd
httpstan/stan.pyx

Knowing the version of httpstan tells us what version of Stan is in use.
Stan version information is redundant.
This commit eliminates 28 unnecessary lines of code. Removing `stan.pyx`
simplifies building the httpstan wheel.

fix: Remove unnecessary Stan version information

---

.travis.yml
Makefile
Makefile.libraries

This makes the Makefile rules much better organized.  In particular, the httpstan Makefile now uses Stan Math's Makefile rules to build the shared libraries used by Stan Math. This relieves httpstan developers of the burden of maintaining complex Makefile rules.
Also adjusts the CI cache directory so builds are independent.
Closes #337 #336

fix: Clean up Makefile rules

---

.travis.yml
httpstan/services_stub.py
httpstan/socket_logger.hpp
httpstan/socket_writer.hpp
httpstan/views.py

Sending datagram messages (à la UDP) is extremely convenient. The code
was readable. Unfortunately, macOS has a very small send buffer. The
Stan logger and writer callbacks (which send us draws) send a lot of
messages and exceed the capacity of the buffer on macOS.
So we use the stream protocol instead. Stan will have to wait until we
are ready to send us draws.

fix: Use stream instead of datagram over socket

---

httpstan/anonymous_stan_model_services.pyx.template
httpstan/services_stub.py

If a C++ exception occurs during the stan::services call (e.g.,
initialization failure) we need to close the sockets which send Stan
messages to httpstan. This is important because failing to close them
might mean there are lingering messages which are never received.  These
messages will likely contain information relevant to figuring out why
the exception occurred.

fix: Close sockets when an exception occurs during sampling

---

httpstan/services_stub.py
httpstan/views.py

The correct place to flush the messages file is after the stan services
call has returned. Flushing it before that point does not make as much
sense.
This change is made out of an abundance of caution about possible race
conditions.

fix: Flush messages_file after stan services call returns

---

httpstan/models.py
httpstan/services/arguments.py

The functionality provided by `pkg_resources` now exists in the Python
standard library. Use of `pkg_resources` is deprecated. See the
`importlib` documentation for more details.
Closes #269

fix: Use importlib, not deprecated pkg_resources

---

.travis.yml

Compiling httpstan sometimes takes longer than 10 minutes on macOS.
Use `travis_wait` to extend timeout to 20 minutes.

ci: Fix for macOS build timeout on travis

---

httpstan/__init__.py
pyproject.toml

This will be the last version of httpstan which uses Stan 2.19.
1.1.3 differs from 1.1.2 in that it uses process-based parallelism
instead of thread-based parallelism. This may have performance
implications for models which can draw all their samples very quickly
(e.g., in a couple of seconds).

chore: Update version

---

pyproject.toml

Fixes a typo in the previous version. The previous version was: `libsundials.*`.
This misses all the files we want since they have the following filenames:
httpstan/lib/libsundials_cvodes.a
httpstan/lib/libsundials_idas.a
httpstan/lib/libsundials_kinsol.a
httpstan/lib/libsundials_nvecserial.a

fix: Include built shared libraries in wheel

---

pyproject.toml

stanc is ignored in `.gitignore`, so poetry does not include it
unless instructed to.

fix: Include stanc in package

---

httpstan/compile.py

The full path to the stanc binary needs to be used in order to run the
stanc executable. Since the stanc binary could be installed anywhere, we
must retrieve the path using `importlib`.
This and previous pull requests are fixing bugs that are not detected by the current CI infrastructure. See #365

fix: Use correct path to stanc binary

---

.travis.yml

Previously we tested in an environment which might be called poetry's
"developer mode". Now we build a wheel, install the wheel, and test.
Running tests in this sort of environment is better because the
environment resembles the one users will have.
Closes #365

ci: Build and install wheel, then run tests

---

.travis.yml
doc/development_setup.rst
tox.ini

The newest version of mypy-protobuf 1.22 generates type annotations
which mypy does not recognize as valid.
Closes #377

fix: Pin mypy-protobuf version, update mypy

---

.travis.yml
build.py
httpstan/empty.pyx
pyproject.toml

The wheel building and repairing machinery recognizes packages as
containing platform-specific modules by the presence of distutils
Extension metadata. This commit adds an empty extension module so the
wheel building machinery is not confused. (httpstan has
platform-specific content (shared libraries) but no build-time extension
modules.)

fix: Fix wheel building with empty extension module

---

httpstan/build_ext.py
httpstan/cache.py
httpstan/models.py
httpstan/services/arguments.py
httpstan/services_stub.py
httpstan/views.py
pyproject.toml
tests/test_arguments.py
tests/test_cache.py

This is a big refactor.
Goal: Compile a model-specific stan::services-wrapping extension module (the kind backed by anonymous_stan_model_services.pyx.template) once, saving it in ~/.cache/httpstan/n.n.n/models/{ model_id } folder. It will be imported from this location every time it is used.
This eliminates the need to save the extension module in a database and extract it into a temporary directory every time it is used.
Closes #385

Refactor model-specific stan::services extension module building

---

Makefile

CI tests periodically fail due to some sort of problem with the `stanc`
executable. With this commit, stanc will be downloaded without
`-silent`.
Closes #380

fix: Do not download stanc silently

---

pyproject.toml

Poetry 1.1 asks for a new `[build-system]` block:
[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

fix: Update to poetry 1.1

---

httpstan/app.py
httpstan/cache.py
httpstan/views.py
tests/test_arguments.py
tests/test_cache.py

Store current operations in memory, not in sqlite. There is
no need to persist operations. Using sqlite is virtually
certain to be slower. Using sqlite also adds complexity:
creating the table, opening and closing a connection.
We do not use threads so there is no thread-safety
concern.
The load_fit and dump_fit functions are now not async. They never needed to be async.

fix: Store current operations in memory

---

httpstan/services_stub.py

Avoid effectively blocking the asyncio loop during sampling by
`sleep`ing briefly when there are no messages to process. Previously
`select` would completely monopolize the CPU until sampling had
completed. As a result, the server would not process simple GET
requests, including the request to learn the current sampling progress.
With this change, such requests are processed.
Second commit contains a very minor performance improvement.

fix: Do not starve asyncio loop during sampling

---

httpstan/anonymous_stan_model_services.pyx.template
httpstan/stan.pxd

Make minor changes to better align Cython code with Cmdstan's
command.hpp. If and when people are interested in understanding how this
wrapping code works it will be helpful to have all code which
does the same thing look approximately the same. For example,
CmdStan references the model with an instance of model_base, so now we
do as well. No changes here change behavior.

refactor: Align Cython code better with CmdStan

---

doc/developer_resources.rst
httpstan/build_ext.py
httpstan/config.py
httpstan/services_stub.py
tests/test_debug_model.py

Add a debug mode which can be enabled via the HTTPSTAN_DEBUG environment variable.
If `HTTPSTAN_DEBUG` is set, httpstan will not run sampling calls in a
background thread or process. This makes debugging via `gdb` much
easier.
Closes #390

feat: Add debug mode

---

httpstan/app.py

aiohttp accepts requests which have at most `client_max_size` bytes.
`client_max_size` must be an integer, not `None`.
Setting this value to the absurdly high value of 512 GiB.
If users are fitting models on with this much data they likely
know enough to patch httpstan.
Closes #417

fix: Use int value for `client_max_size`

---

.travis.yml
README.rst
doc/index.rst

Remove unused codecov line in travis config.
Remove reference to unused coveralls service in docs.

ci: Remove unused coverage config, docs

---

httpstan/compile.py
tests/test_compile.py

Use an informative scheme for temporary filename in compile function.
Add "--warn-pedantic" in stanc call.

feat: informative compile filename

---

httpstan/cache.py
httpstan/openapi.py
httpstan/routes.py
httpstan/views.py
tests/test_cache.py
tests/test_programs.py

Allows users to list models in cache. REST APIs
typically offer such a list.
Such a list is required if a user wants to delete
all models from the cache. This is because, without
this function, there is no way for the user to know
what models are in the cache. Models must be referred
to by name in order to delete them.
Closes #409

feat: Add list_models endpoint

---

.travis.yml

Bug which affects `poetry export` is unfixed in 1.1.0.
Fixed in future releases.
See https://github.com/python-poetry/poetry/issues/3063

ci: Hotfix, avoid poetry 1.1.0

---

.travis.yml

Verify that httpstan does not break pystan by
importing pystan and sampling from a simple model.

ci: Verify that httpstan does not break pystan

---

.gitignore
Makefile
httpstan/models.py
pyproject.toml

This will dramatically speed up compilation of the model-specific Python extensions. The strategy here mirrors the strategy used by CmdStan.

Precompile stan_services.cpp

---

.travis.yml

Use Ubuntu 20.04 for tests and add Python 3.9.
This draft PR is for testing Python 3.9. When Python 3.9 is released the "-dev" can be dropped and the PR merged.

ci: Update CI config for Python 3.9

---

.travis.yml

Newer versions of poetry do not export dev-dependencies extras
correctly. See https://github.com/python-poetry/poetry/issues/2909

ci: Use working version of poetry

---

Makefile

Use g++ instead of gcc when pre-commpiling C++ code.
This does not appear to matter with gcc 9.3 but may
matter with older versions of gcc.

fix: Use g++ instead of gcc when pre-compiling

---

httpstan/build_ext.py

Previously the invocations of the compiler and linker
were not shown.

feat: Show compiler args when debug mode is on

---

Makefile
pyproject.toml

Use newer versions of the following packages:
- apispec
- numpy
- protobuf
Choice of numpy 1.16 reflects:
https://numpy.org/neps/nep-0029-deprecation_policy.html

chore: Use newer versions of packages

---

Makefile

Remove hard-coded shared library version from Makefile.  Only affects
macOS.

fix: Remove hard-coded shared library version

---

tests/test_sampling_exceptions.py

Verify that failing to provide a variable defined in the `data` block
raises the appropriate exception.
See https://github.com/stan-dev/pystan-next/issues/137 for original
report.

tests: Verify missing data raises exception

---

README.rst
doc/index.rst
httpstan/socket_logger.hpp
httpstan/socket_writer.hpp
protos/callbacks_writer.proto
tests/helpers.py
tests/test_sampling_exceptions.py

Use `bytes` not `string`s in Protocol Buffers messages. According to the
protocol buffers specification, `string`s may only be used when one can
guarantee that the underlying bytes are valid UTF-8.  (We use C++
`std::string`s and perform no checking that anything is valid UTF-8.)
According to the spec, we must use Protocol Buffer `bytes`.
This may address a mysterious bug on macOS that seems to involve
a failure in the encoding (or decoding) of a protocol buffer message.
This is a breaking change since we are changing the protocol buffer
schema.
Note for reviewers: There are no substantive changes here except replacing protobuf `string` types with protobuf `bytes` types.

BREAKING CHANGE: Use bytes not strings in protobuf messages

---

Makefile
httpstan/services_stub.py
httpstan/socket_logger.hpp
httpstan/socket_writer.hpp

Send the entire message over the socket. Previously, if the message was
larger than the send or receive buffer size (8192 bytes on macOS), a
partial message would be sent. The boost function boost::asio::send
makes sure that the entire message is sent.

fix: Send entire message over the socket

---

.travis.yml

Remove non-working Linux jobs with clang.  Exporting CC=clang is not
sufficient to have libraries be built using clang. So these CI jobs are
not doing what they intend to do.

ci: Remove non-working Linux jobs with clang

---

httpstan/cache.py
httpstan/services_stub.py
httpstan/views.py
pyproject.toml
tests/helpers.py
tests/test_bernoulli.py

Compress draws and messages from Stan using LZ4.  Previously gzip was
used. (LZ4 is much faster than gzip.) This commit also removes
compression/decompression steps from the `load_fit` and `dump_fit`
functions. Cache functions should be as simple as possible. In
particular, they should not need to know the format of data being
stored.  That said, an indication of format remains in the filename
`jsonlines.lz4`.  This is unfortunate and should be addressed in a
future commit.
Closes #485

feat: Compress draws and messages using LZ4

---

httpstan/openapi.py
httpstan/routes.py
httpstan/schemas.py
httpstan/stan_services.cpp
httpstan/views.py
tests/test_log_prob.py

Given a model name, associated data and unconstrained parameters,
the log_prob endpoint will calculate and return the log probability
of the unconstrained parameters.
This feature is accompanied by two tests, both of which are based on
a simple Gaussian problem: the first test validates the log_prob endpoint
by comparing the output against the analytically derived log probability;
the second test validates the log_prob endpoint by comparing the output
against the log probability (lp__) extracted from a model fit.
Closes #113

feat: Add log_prob method and endpoint

---

httpstan/stan_services.cpp
httpstan/views.py

Previously, the log_prob endpoint called the
log_prob_propto method in the stan::model namespace.
This fix calls the log_prob method of the model  class instead.

fix: Call log_prob method of model class

---

httpstan/openapi.py
httpstan/routes.py
httpstan/schemas.py
httpstan/stan_services.cpp
httpstan/views.py
tests/test_log_prob_grad.py

Given a model name, associated data and unconstrained parameters,
the log_prob_grad endpoint will calculate and return the gradient
of the unconstrained parameters.
This feature is accompanied by a test: the log_prob_grad method is
validated on a simple Gaussian example, the test compares the output
of the endpoint against an analytical calculation of the gradient.

feat: Add log_prob_grad method and endpoint

---

httpstan/openapi.py
httpstan/routes.py
httpstan/schemas.py
httpstan/stan_services.cpp
httpstan/views.py
tests/test_write_array.py

Given a model name, associated data and unconstrained parameters,
the write_array endpoint will transform the sequence of unconstrained
parameters to their defined support, optionally including transformed
parameters and generated quantities.

feat: Add write_array method and endpoint

---

httpstan/views.py
tests/test_sampling_exceptions.py

Do not save any messages from failed sampling runs.
For example, if sampling starts but cannot continue because attempts
to find appropriate initial values are rejected, there will be some
(logger) messages saved to disk. The presence of these messages
confuses the cache machinery, which assumes the presence of messages
on disk indicates a successful fit. Deleting them avoids the problem.
There remains the problem of retrieving the logger messages associated
with the failed fit. It's possible that this is something someone might
want to do. Future work might address this. Such a user is also free to
use CmdStan.
Closes #452

fix: Do not save messages from failed fits

---

pyproject.toml

Effectively disable coverage `fail_under` by setting it to 20%.
The existing coverage setup has made developing httpstan harder.
Proposed additions which have tests would cause the coverage check to
fail.  It was not always clear what piece of code was not checked.

tests: Relax coverage fail_under

---

httpstan/openapi.py
httpstan/routes.py
httpstan/schemas.py
httpstan/stan_services.cpp
httpstan/views.py
tests/test_transform_inits.py

Given a model name, associated data, and constrained parameter
values and their context, the transformed_inits endpoint will
unconstrain the constrained parameters from their defined
support to unconstrained space.

feat: Add transform_inits method and endpoint

---

Makefile

Avoid creating symlinks to shared libraries because these
risk being ignored by Python wheel builders.

fix: Avoid creating symlinks to shared libraries

---

docs-requirements.txt

Add missing requirement for docs building.
Closes #526

fix: Add missing requirement for docs building

---

Makefile
build.py
httpstan/utils.py

Update pybind11 to version 2.6.2. Use the recommended
-fvisibility=hidden compiler flag when compiling C++ code which uses the
pybind11 library.
Closes #478

feat: Update pybind11, add recommended flag

---

README.rst
doc/index.rst

Fix link to PyPI shield/badge.
Closes #528

docs: Fix link to PyPI shield/badge [ci skip]

---

doc/contributing.rst

Add mention of the Google JSON Style Guide. The Guide describes
naming conventions not covered in the API Design Guide.
Closes #504

docs: Add mention of the Google JSON Style Guide [ci skip]

---

.github/stale.yml

Bugs marked as stale after 90 days now.

ci: Make stale bot less active

---

Makefile
httpstan/models.py

refactor: Consistently name source code directories
Place source code directories in `httpstan/include` in a consistent way.
Follows the convention familiar from Unix-like systems. Users should
only need to add `httpstan/include` as a search path for third-party
source files. Previously many more search paths needed to be specified.
Closes #469

fix: Place libs required by Stan Math in include

---

httpstan/models.py

Use asyncio.get_running_loop everywhere. Elsewhere, in a similar call,
we use asyncio.get_running_loop. This commit eliminates the
inconsistency.  asyncio.get_running_loop is the function we want. It
raises an exception if an event loop does not exist.

fix: Use asyncio.get_running_loop everywhere

---

httpstan/empty.cpp
httpstan/schemas.py
httpstan/stan_services.cpp
tests/test_fixed_param.py

Let users call `stan::services::sample::fixed_param` in addition
to `stan::services::sample::hmc_nuts_diag_e_adapt`.
This commit is simple: a copy and paste of the `stan::services::sample::hmc_nuts_diag_e_adapt` wrapper, then trim some of the args which fixed_param does not use.
Ran clang-format as a separate commit.

feat: Allow calling stan::services::sample::fixed_param

---

README.rst
doc/index.rst

docs: Fix typo in README [ci skip]

---

README.rst
doc/index.rst

Use a simplified citation. This avoids having to deal with Zenodo
during every release.

docs: Simplify citation

---

Makefile

Add rule to allow macOS to use parallel make.
Closes #557

fix: Fix parallel make on macOS

---

httpstan/services_stub.py

Require multiprocessing to use the "fork" method for starting
new processes. This is the only version httpstan currently works
with. (macOS recently switched to "spawn" as the default.)
This follows the recommendation in the Python `multiprocessing`
documentation:
> A library which wants to use a particular start method should probably
> use get_context() to avoid interfering with the choice of the library
> user.

fix: Require multiprocessing to use "fork"

---

httpstan/services_stub.py
httpstan/views.py

Interrupting sampling makes much less noise now as KeyboardInterrupt
is ignored by the worker processes. Commit also avoids
raising an additional exception when a KeyboardInterrupt stops
sampling.
Stopping sampling via control-c occurs in PyStan. This change
should not affect anyone using httpstan by itself.

feat: Handle control-c with less noise

---

httpstan/cache.py
httpstan/views.py
tests/test_cache.py
tests/test_delete_fit.py

Use the already established (Pythonic) idiom for deleting fits.
Raise a KeyError if the to-be-deleted fit does not exist.

fix: Use established idiom for deleting fits

---

scripts/tag-release

Add a script which helps tag releases.
This should help avoid accidental mistakes.

ci: Add tag-release script

---

README.rst
doc/installation.rst

Python version requirements are also better communicated by PyPI.

docs: Drop outdated mention of Python 3.7

---

httpstan/services_stub.py
httpstan/views.py
pyproject.toml
tests/test_sampling_exceptions.py

When Stan is unable to initialize a chain, it aborts with an
"Initialization failed" error message. Prior to issuing this error
message, Stan emits potentially useful informational messages, such as
"Rejecting initial value: Log probability evaluates to log(0)".
Previously, these messages were not included in the exception.
Closes #595

feat: Add context to initialization failed error

---

pyproject.toml

openapi-spec-validator version 0.5 introduced breaking changes.

docs: Address breaking change in openapi-spec-validator

---

pyproject.toml

All build dependencies must specified in pyproject.toml. We depend on setuptools.
Background: Poetry 1.2 came out recently. Poetry (and everyone else) make use of the PEP517 spec describing how packages can be built without using a setup.py.
Closes #618

fix: Require setuptools in build environment

---

build.py
httpstan/build_ext.py
pyproject.toml

distutils is being removed from the Python standard library. A copy exists in setuptools. Use that.
Closes #573

feat: Stop using distutils (removed in Python 3.12)

---

README.rst
doc/installation.rst

Make clear that wheels need x86-64 arch and that people with other kinds of CPUs will need to install from source.
Minor edits to align pystan and httpstan docs included here as well.

docs: Make clear that wheels need x86-64 arch

---

.github/workflows/main.yml
httpstan/build_ext.py
pyproject.toml

Finish migration from distutils to setuptools. Distutils is being deprecated by Python.
There are minor differences between setuptools and distutils. These differences are not well-documented.
This change appears to make things work.
A better approach would be to subclass build_ext, following the
guidelines in the setuptools documentation:
https://setuptools.pypa.io/en/latest/userguide/extension.html
Closes https://github.com/stan-dev/httpstan/issues/631

Finish migration to setuptools

---

.github/workflows/main.yml

macos 10.15 runners are no longer available.

ci(macos): Remove unsupported macos 10.15 runners
